import { shortQueries, hookQueries, mediaQueries } from '@/lib/db/queries';
import { renderQueue } from './render-queue';
import { generateId } from './utils';
import { generateSingleHook, refillHookPool } from './hook-generator';

export interface AutoGenerateResult {
  shortId: string;
  hookText: string;
  mediaCount: number;
  status: 'draft' | 'rendering';
}

/** Número de shorts automáticos al día (configurable por env, por defecto 2). */
export function getDailyShortLimit(): number {
  const raw = Number(process.env.SHORTS_PER_DAY);
  if (Number.isFinite(raw) && raw > 0) return Math.min(Math.floor(raw), 10);
  return 2;
}

/** Cuenta cuántos shorts auto-generados de hoy hay (sin contar fallidos). */
export async function countAutoGeneratedToday(): Promise<number> {
  const now = new Date();
  const todayStart = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const tomorrowStart = new Date(now.getFullYear(), now.getMonth(), now.getDate() + 1);

  const todayShorts = await shortQueries.findAll();
  return todayShorts.filter(
    short =>
      short.status !== 'failed' &&
      short.tags?.includes('auto') &&
      new Date(short.created_at) >= todayStart &&
      new Date(short.created_at) < tomorrowStart
  ).length;
}

export async function autoGenerateShort(mediaIds: string[]): Promise<AutoGenerateResult | null> {
  if (!mediaIds.length) return null;

  // Cuando queden pocos hooks activos, reabastece el pool con Zen (hasta 100 hooks).
  try {
    const created = await refillHookPool();
    if (created > 0) console.log(`[AutoGenerate] Refill: ${created} hooks creados via OpenCode Zen`);
  } catch (e: any) {
    console.error(`[AutoGenerate] Hook refill failed: ${e.message}`);
  }

  // Usa OpenCode Zen (big-pickle) para generar un hook fresco para este short.
  const mediaSnapshot = await mediaQueries.findByIds(mediaIds);
  const context = mediaSnapshot
    .map(m => m.name)
    .join(', ');

  let hookText = '';
  try {
    hookText = await generateSingleHook(context);
  } catch (e: any) {
    console.error(`[AutoGenerate] Zen hook failed: ${e.message}`);
  }

  // Si Zen no devolvió nada, usa un hook activo existente o crea uno de fallback.
  if (!hookText) {
    let activeHooks: { text: string }[] = await hookQueries.findActive();
    if (!activeHooks.length) {
      const fallbackHookText = '¿Necesitas un CV que realmente atraiga clientes?';
      activeHooks = [await hookQueries.create(fallbackHookText)];
    }
    hookText = activeHooks[Math.floor(Math.random() * activeHooks.length)].text;
  }

  // Registra el hook en la tabla hooks para que participe en analytics y gestión.
  const storedHook = await hookQueries.create(hookText);

  const short = await shortQueries.create({
    id: generateId(),
    hookId: storedHook.id,
    hookText,
    mediaIds,
    title: 'Short Auto-generado',
    description: '',
    tags: ['shorts', 'auto'],
    status: 'draft',
  });

  if (!short) return null;

  renderQueue.add(short.id);

  return {
    shortId: short.id,
    hookText,
    mediaCount: mediaIds.length,
    status: 'rendering',
  };
}

function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

/** Reparte los medios entre N shorts intentando no repetir medios dentro del mismo día. */
function buildMediaBatches(allMedia: { id: string; created_at: string }[], count: number, maxPerBatch: number): string[][] {
  const sorted = [...allMedia].sort(
    (a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
  );

  const batches: string[][] = [];
  for (let i = 0; i < count; i++) {
    const slice = sorted.slice(i * maxPerBatch, i * maxPerBatch + maxPerBatch);
    if (slice.length) {
      batches.push(slice.map(m => m.id));
    } else if (sorted.length) {
      const fallback = shuffle(sorted).slice(0, maxPerBatch);
      batches.push(fallback.map(m => m.id));
    }
  }
  return batches;
}

/**
 * Genera UN short manual sin límite diario ni sync.
 * Cada vez que se pulsa el botón llama a OpenCode Zen para conseguir
 * un hook nuevo y selecciona un puñado de medios al azar.
 */
export async function generateOneManualShort(): Promise<AutoGenerateResult | null> {
  const allMedia = await mediaQueries.findAll();
  if (!allMedia.length) return null;

  const mediaIds = shuffle(allMedia)
    .slice(0, Math.min(4, allMedia.length))
    .map(m => m.id);

  return autoGenerateShort(mediaIds);
}

export async function syncAndGenerate(): Promise<{ synced: number; generated: number; errors: string[] }> {
  const errors: string[] = [];
  let synced = 0;
  let generated = 0;

  try {
    // 1. Medios locales (carpetas videos/ y fotos/)
    const { syncLocalMedia } = await import('./local-sync');
    const localResult = await syncLocalMedia();
    synced += localResult.newMediaCount;
    errors.push(...localResult.errors);
  } catch (e: any) {
    errors.push(`Local sync failed: ${e.message}`);
  }

  // 2. Medios desde GitHub (si está configurado)
  try {
    const { syncGitHubMedia } = await import('./github');
    const ghResult = await syncGitHubMedia();
    synced += ghResult.newMediaCount;
    errors.push(...ghResult.errors);
  } catch (e: any) {
    errors.push(`GitHub sync failed: ${e.message}`);
  }

  // 3. Generar hasta el límite diario (2 por defecto), aunque no haya medios nuevos.
  const dailyLimit = getDailyShortLimit();
  const alreadyToday = await countAutoGeneratedToday();
  const toGenerate = Math.max(0, dailyLimit - alreadyToday);

  if (toGenerate > 0) {
    try {
      const allMedia = await mediaQueries.findAll();
      if (allMedia.length > 0) {
        const batches = buildMediaBatches(allMedia, toGenerate, 4);
        for (const mediaIds of batches) {
          const result = await autoGenerateShort(mediaIds);
          if (result) generated++;
        }
      } else {
        errors.push('No hay medios disponibles para generar shorts');
      }
    } catch (e: any) {
      errors.push(`Auto-generate failed: ${e.message}`);
    }
  }

  return { synced, generated, errors };
}